apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: https://github.com/hazem-internship/gow-new-1.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: hazem-internship
    repository: new-onpremises
  - key: staging
  - key: production
  ingress:
    domain: 10.0.0.100.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: hazemTa
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
