filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-observability
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: grafana
  url: https://hazem-internship.github.io/gow-new-1
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
- chart: grafana/grafana
  version: 6.17.4
  name: grafana
  values:
  - ../../versionStream/charts/grafana/grafana/values.yaml.gotmpl
  - jx-values.yaml
- chart: prometheus-community/prometheus
  version: 13.6.0
  name: prometheus
  values:
  - ../../versionStream/charts/prometheus-community/prometheus/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
